// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: literal.proto
// Protobuf Java Version: 4.26.1

package co.gaffe.proto;

public final class LiteralOuterClass {
  private LiteralOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
