// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: literal.proto

// Protobuf Java Version: 4.26.1
package co.gaffe.proto;

public interface LiteralOrBuilder extends
    // @@protoc_insertion_point(interface_extends:co.gaffe.proto.Literal)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.co.gaffe.proto.DataType null = 1;</code>
   * @return Whether the null field is set.
   */
  boolean hasNull();
  /**
   * <code>.co.gaffe.proto.DataType null = 1;</code>
   * @return The null.
   */
  co.gaffe.proto.DataType getNull();

  /**
   * <code>bytes binary = 2;</code>
   * @return Whether the binary field is set.
   */
  boolean hasBinary();
  /**
   * <code>bytes binary = 2;</code>
   * @return The binary.
   */
  com.google.protobuf.ByteString getBinary();

  /**
   * <code>bool boolean = 3;</code>
   * @return Whether the boolean field is set.
   */
  boolean hasBoolean();
  /**
   * <code>bool boolean = 3;</code>
   * @return The boolean.
   */
  boolean getBoolean();

  /**
   * <code>int32 byte = 4;</code>
   * @return Whether the byte field is set.
   */
  boolean hasByte();
  /**
   * <code>int32 byte = 4;</code>
   * @return The byte.
   */
  int getByte();

  /**
   * <code>int32 short = 5;</code>
   * @return Whether the short field is set.
   */
  boolean hasShort();
  /**
   * <code>int32 short = 5;</code>
   * @return The short.
   */
  int getShort();

  /**
   * <code>int32 integer = 6;</code>
   * @return Whether the integer field is set.
   */
  boolean hasInteger();
  /**
   * <code>int32 integer = 6;</code>
   * @return The integer.
   */
  int getInteger();

  /**
   * <code>int64 long = 7;</code>
   * @return Whether the long field is set.
   */
  boolean hasLong();
  /**
   * <code>int64 long = 7;</code>
   * @return The long.
   */
  long getLong();

  /**
   * <code>float float = 10;</code>
   * @return Whether the float field is set.
   */
  boolean hasFloat();
  /**
   * <code>float float = 10;</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <code>double double = 11;</code>
   * @return Whether the double field is set.
   */
  boolean hasDouble();
  /**
   * <code>double double = 11;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <code>.co.gaffe.proto.Literal.Decimal decimal = 12;</code>
   * @return Whether the decimal field is set.
   */
  boolean hasDecimal();
  /**
   * <code>.co.gaffe.proto.Literal.Decimal decimal = 12;</code>
   * @return The decimal.
   */
  co.gaffe.proto.Literal.Decimal getDecimal();

  /**
   * <code>string string = 13;</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <code>string string = 13;</code>
   * @return The string.
   */
  java.lang.String getString();
  /**
   * <code>string string = 13;</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <pre>
   * Date in units of days since the UNIX epoch.
   * </pre>
   *
   * <code>int32 date = 16;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <pre>
   * Date in units of days since the UNIX epoch.
   * </pre>
   *
   * <code>int32 date = 16;</code>
   * @return The date.
   */
  int getDate();

  /**
   * <pre>
   * Timestamp in units of microseconds since the UNIX epoch.
   * </pre>
   *
   * <code>int64 timestamp = 17;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * Timestamp in units of microseconds since the UNIX epoch.
   * </pre>
   *
   * <code>int64 timestamp = 17;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Timestamp in units of microseconds since the UNIX epoch (without timezone information).
   * </pre>
   *
   * <code>int64 timestamp_ntz = 18;</code>
   * @return Whether the timestampNtz field is set.
   */
  boolean hasTimestampNtz();
  /**
   * <pre>
   * Timestamp in units of microseconds since the UNIX epoch (without timezone information).
   * </pre>
   *
   * <code>int64 timestamp_ntz = 18;</code>
   * @return The timestampNtz.
   */
  long getTimestampNtz();

  /**
   * <code>.co.gaffe.proto.Literal.CalendarInterval calendar_interval = 19;</code>
   * @return Whether the calendarInterval field is set.
   */
  boolean hasCalendarInterval();
  /**
   * <code>.co.gaffe.proto.Literal.CalendarInterval calendar_interval = 19;</code>
   * @return The calendarInterval.
   */
  co.gaffe.proto.Literal.CalendarInterval getCalendarInterval();

  /**
   * <code>int32 year_month_interval = 20;</code>
   * @return Whether the yearMonthInterval field is set.
   */
  boolean hasYearMonthInterval();
  /**
   * <code>int32 year_month_interval = 20;</code>
   * @return The yearMonthInterval.
   */
  int getYearMonthInterval();

  /**
   * <code>int64 day_time_interval = 21;</code>
   * @return Whether the dayTimeInterval field is set.
   */
  boolean hasDayTimeInterval();
  /**
   * <code>int64 day_time_interval = 21;</code>
   * @return The dayTimeInterval.
   */
  long getDayTimeInterval();

  /**
   * <code>.co.gaffe.proto.Literal.Array array = 22;</code>
   * @return Whether the array field is set.
   */
  boolean hasArray();
  /**
   * <code>.co.gaffe.proto.Literal.Array array = 22;</code>
   * @return The array.
   */
  co.gaffe.proto.Literal.Array getArray();

  /**
   * <code>.co.gaffe.proto.Literal.Map map = 23;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <code>.co.gaffe.proto.Literal.Map map = 23;</code>
   * @return The map.
   */
  co.gaffe.proto.Literal.Map getMap();

  /**
   * <code>.co.gaffe.proto.Literal.Struct struct = 24;</code>
   * @return Whether the struct field is set.
   */
  boolean hasStruct();
  /**
   * <code>.co.gaffe.proto.Literal.Struct struct = 24;</code>
   * @return The struct.
   */
  co.gaffe.proto.Literal.Struct getStruct();

  public co.gaffe.proto.Literal.LiteralTypeCase getLiteralTypeCase();
}
