// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto
// Protobuf Java Version: 4.26.1

package co.gaffe.proto;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
