// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasmudf.proto

// Protobuf Java Version: 4.26.1
package co.gaffe.proto;

/**
 * Protobuf type {@code co.gaffe.proto.UDFArgs}
 */
public  final class UDFArgs extends
    com.google.protobuf.GeneratedMessageLite<
        UDFArgs, UDFArgs.Builder> implements
    // @@protoc_insertion_point(message_implements:co.gaffe.proto.UDFArgs)
    UDFArgsOrBuilder {
  private UDFArgs() {
    args_ = emptyProtobufList();
  }
  public static final int ARGS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<co.gaffe.proto.Literal> args_;
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  @java.lang.Override
  public java.util.List<co.gaffe.proto.Literal> getArgsList() {
    return args_;
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  public java.util.List<? extends co.gaffe.proto.LiteralOrBuilder> 
      getArgsOrBuilderList() {
    return args_;
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  @java.lang.Override
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  @java.lang.Override
  public co.gaffe.proto.Literal getArgs(int index) {
    return args_.get(index);
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  public co.gaffe.proto.LiteralOrBuilder getArgsOrBuilder(
      int index) {
    return args_.get(index);
  }
  private void ensureArgsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<co.gaffe.proto.Literal> tmp = args_;
    if (!tmp.isModifiable()) {
      args_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void setArgs(
      int index, co.gaffe.proto.Literal value) {
    value.getClass();
  ensureArgsIsMutable();
    args_.set(index, value);
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void addArgs(co.gaffe.proto.Literal value) {
    value.getClass();
  ensureArgsIsMutable();
    args_.add(value);
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void addArgs(
      int index, co.gaffe.proto.Literal value) {
    value.getClass();
  ensureArgsIsMutable();
    args_.add(index, value);
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void addAllArgs(
      java.lang.Iterable<? extends co.gaffe.proto.Literal> values) {
    ensureArgsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, args_);
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void clearArgs() {
    args_ = emptyProtobufList();
  }
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  private void removeArgs(int index) {
    ensureArgsIsMutable();
    args_.remove(index);
  }

  public static co.gaffe.proto.UDFArgs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static co.gaffe.proto.UDFArgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static co.gaffe.proto.UDFArgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static co.gaffe.proto.UDFArgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(co.gaffe.proto.UDFArgs prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code co.gaffe.proto.UDFArgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        co.gaffe.proto.UDFArgs, Builder> implements
      // @@protoc_insertion_point(builder_implements:co.gaffe.proto.UDFArgs)
      co.gaffe.proto.UDFArgsOrBuilder {
    // Construct using co.gaffe.proto.UDFArgs.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    @java.lang.Override
    public java.util.List<co.gaffe.proto.Literal> getArgsList() {
      return java.util.Collections.unmodifiableList(
          instance.getArgsList());
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    @java.lang.Override
    public int getArgsCount() {
      return instance.getArgsCount();
    }/**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    @java.lang.Override
    public co.gaffe.proto.Literal getArgs(int index) {
      return instance.getArgs(index);
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder setArgs(
        int index, co.gaffe.proto.Literal value) {
      copyOnWrite();
      instance.setArgs(index, value);
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder setArgs(
        int index, co.gaffe.proto.Literal.Builder builderForValue) {
      copyOnWrite();
      instance.setArgs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder addArgs(co.gaffe.proto.Literal value) {
      copyOnWrite();
      instance.addArgs(value);
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder addArgs(
        int index, co.gaffe.proto.Literal value) {
      copyOnWrite();
      instance.addArgs(index, value);
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder addArgs(
        co.gaffe.proto.Literal.Builder builderForValue) {
      copyOnWrite();
      instance.addArgs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder addArgs(
        int index, co.gaffe.proto.Literal.Builder builderForValue) {
      copyOnWrite();
      instance.addArgs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends co.gaffe.proto.Literal> values) {
      copyOnWrite();
      instance.addAllArgs(values);
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder clearArgs() {
      copyOnWrite();
      instance.clearArgs();
      return this;
    }
    /**
     * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
     */
    public Builder removeArgs(int index) {
      copyOnWrite();
      instance.removeArgs(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:co.gaffe.proto.UDFArgs)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new co.gaffe.proto.UDFArgs();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "args_",
            co.gaffe.proto.Literal.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<co.gaffe.proto.UDFArgs> parser = PARSER;
        if (parser == null) {
          synchronized (co.gaffe.proto.UDFArgs.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<co.gaffe.proto.UDFArgs>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:co.gaffe.proto.UDFArgs)
  private static final co.gaffe.proto.UDFArgs DEFAULT_INSTANCE;
  static {
    UDFArgs defaultInstance = new UDFArgs();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UDFArgs.class, defaultInstance);
  }

  public static co.gaffe.proto.UDFArgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UDFArgs> PARSER;

  public static com.google.protobuf.Parser<UDFArgs> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

