// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasmudf.proto

// Protobuf Java Version: 4.26.1
package co.gaffe.proto;

public interface UDFArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:co.gaffe.proto.UDFArgs)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  java.util.List<co.gaffe.proto.Literal> 
      getArgsList();
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  co.gaffe.proto.Literal getArgs(int index);
  /**
   * <code>repeated .co.gaffe.proto.Literal args = 1;</code>
   */
  int getArgsCount();
}
