// source: wasmudf.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var types_pb = require('./types_pb.js');
goog.object.extend(proto, types_pb);
var literal_pb = require('./literal_pb.js');
goog.object.extend(proto, literal_pb);
goog.exportSymbol('proto.co.gaffe.proto.UDFArgs', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.co.gaffe.proto.UDFArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.co.gaffe.proto.UDFArgs.repeatedFields_, null);
};
goog.inherits(proto.co.gaffe.proto.UDFArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.co.gaffe.proto.UDFArgs.displayName = 'proto.co.gaffe.proto.UDFArgs';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.co.gaffe.proto.UDFArgs.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.co.gaffe.proto.UDFArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.co.gaffe.proto.UDFArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.co.gaffe.proto.UDFArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.co.gaffe.proto.UDFArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    argsList: jspb.Message.toObjectList(msg.getArgsList(),
    literal_pb.Literal.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.co.gaffe.proto.UDFArgs}
 */
proto.co.gaffe.proto.UDFArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.co.gaffe.proto.UDFArgs;
  return proto.co.gaffe.proto.UDFArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.co.gaffe.proto.UDFArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.co.gaffe.proto.UDFArgs}
 */
proto.co.gaffe.proto.UDFArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new literal_pb.Literal;
      reader.readMessage(value,literal_pb.Literal.deserializeBinaryFromReader);
      msg.addArgs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.co.gaffe.proto.UDFArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.co.gaffe.proto.UDFArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.co.gaffe.proto.UDFArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.co.gaffe.proto.UDFArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArgsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      literal_pb.Literal.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Literal args = 1;
 * @return {!Array<!proto.co.gaffe.proto.Literal>}
 */
proto.co.gaffe.proto.UDFArgs.prototype.getArgsList = function() {
  return /** @type{!Array<!proto.co.gaffe.proto.Literal>} */ (
    jspb.Message.getRepeatedWrapperField(this, literal_pb.Literal, 1));
};


/**
 * @param {!Array<!proto.co.gaffe.proto.Literal>} value
 * @return {!proto.co.gaffe.proto.UDFArgs} returns this
*/
proto.co.gaffe.proto.UDFArgs.prototype.setArgsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.co.gaffe.proto.Literal=} opt_value
 * @param {number=} opt_index
 * @return {!proto.co.gaffe.proto.Literal}
 */
proto.co.gaffe.proto.UDFArgs.prototype.addArgs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.co.gaffe.proto.Literal, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.co.gaffe.proto.UDFArgs} returns this
 */
proto.co.gaffe.proto.UDFArgs.prototype.clearArgsList = function() {
  return this.setArgsList([]);
};


goog.object.extend(exports, proto.co.gaffe.proto);
